### ISSUE TITLE
Error displayed on extensions.gnome.org

### ISSUE THREAD

**Issue by manuee** [emerinohdz/power-alt-tab#11]
I have the extension installed already, just noticed this error on the extensions website
![screenshot from 2017-11-20 08-53-42](https://user-images.githubusercontent.com/105582/33009928-5a2a72d6-cdd0-11e7-81cd-ba6c4e4fd7f6.png)

The extension seems to be working fine here, running GNOME Shell 3.18.5 (on Ubuntu Gnome 16.04).

I'm not sure it has anything to do with my version of gnome shell or if its a problem with the website itself.

**Comment by emerinohdz** [comment]
Hello, could you please check the gnome console (alt + f2 and type lg) and see what the error is?

**Comment by manuee** [comment]
Sure thing, I think this could be it :)
![screenshot from 2017-11-20 15-09-41](https://user-images.githubusercontent.com/105582/33025113-e7899fa6-ce04-11e7-8813-ce101fdd2e3d.png)

**Comment by emerinohdz** [comment]
Yeah, I have to give it backwards support for gs <  3.26, I'll submit it today and let you know. Thanks for reporting!

**Comment by manuee** [comment]
Thank you @emerinohdz for caring and maintaining!

**Comment by emerinohdz** [comment]
No problem, I've already submitted the new version to GSE, code is already updated in the repo. 
Regards.

**Comment by manuee** [comment]
Brilliant, working now thanks for the quick turnaround!
