### ISSUE TITLE
Doesn't work with GNOME 3.18

### ISSUE THREAD

**Issue by rrthomas** [emerinohdz/power-alt-tab#12]
It works for a bit, then errors (typically when I'm not using it).

lg shows error "Second argument to Lang.bind() must be a function, not undefined".

I'm using version 22 of the extension, the latest I'm offered by extensions.gnome.org.

**Comment by rrthomas** [comment]
lg shows error "Second argument to Lang.bind() must be a function, not undefined".

I'm using version 22 of the extension, the latest I'm offered by extensions.gnome.org.

**Comment by emerinohdz** [comment]
Hello, that version may be broken for GS 3.18... please try the latest available in this repository, it should support GS 3.18 without problem. Please let me know if you are OK with using gulp or if you need me to provide a packaged ZIP file.

**Comment by rrthomas** [comment]
Thanks for the response. I've installed it with gulp, I'll let you know how it goes.

**Comment by emerinohdz** [comment]
Ok, I'll live this ticket open then.

**Comment by rrthomas** [comment]
Well, 24 hours later it's still working, so it looks good!

**Comment by emerinohdz** [comment]
Great, I'll considere it solved then.

**Comment by rrthomas** [comment]
Thanks!
